const types = {
    ADD_POST: "ADD_POST",
    GET_POST: "GET_POST",
    GET_POSTS: "GET_POSTS",
    EDIT_POST: "EDIT_POST",
    DELETE_POST: "DELETE_POST",
    SIGNUP_USER: "SIGNUP_USER",
    LOGIN_USER: "LOGIN_USER",
    AUTH_TOKEN: "AUTH_TOKEN",
    ERROR: 'ERROR'
}
export default types;